### ISSUE TITLE
Extend example to include skipping on pre-commit ci

### ISSUE THREAD

**Issue by ssbarnea** [mashi/codecov-validator#69]
As currently is not possible to use this hook on pre-commit.ci due to using network access, the installation example should be updated to include
```yaml
ci:
  skip:
    - ccv
```
